<a href="https://colab.research.google.com/github/Ysabellyysa/Python/blob/main/Games.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [2]:
import pandas as pd
import tensorflow as tf
import sklearn

In [3]:
from tensorflow.keras.layers import Dense, Dropout, Activation, Input
from tensorflow.keras.models import Model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [4]:
base = pd.read_csv('games.csv')
base

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
base = base.drop('Other_Sales', axis = 1)
base = base.drop('Global_Sales', axis = 1)
base = base.drop('Developer', axis = 1)

In [6]:
base.shape

(16719, 13)

In [7]:
base.isnull().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Rating             6769
dtype: int64

In [8]:
base = base.dropna(axis = 0)

In [9]:
base.shape

(6825, 13)

In [10]:
base.isnull().sum()

Name               0
Platform           0
Year_of_Release    0
Genre              0
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Critic_Score       0
Critic_Count       0
User_Score         0
User_Count         0
Rating             0
dtype: int64

In [11]:
base['Name'].value_counts()

Name
Madden NFL 07                                   8
Need for Speed: Most Wanted                     8
LEGO Star Wars II: The Original Trilogy         8
Terraria                                        7
Madden NFL 08                                   7
                                               ..
Brain Age: Train Your Brain in Minutes a Day    1
Wii Fit                                         1
Wii Sports Resort                               1
Mario Kart Wii                                  1
Wii Sports                                      1
Name: count, Length: 4377, dtype: int64

In [12]:
base = base.drop('Name', axis = 1)

In [13]:
base.shape

(6825, 12)

In [14]:
base.columns

Index(['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Critic_Score', 'Critic_Count', 'User_Score',
       'User_Count', 'Rating'],
      dtype='object')

In [15]:
X = base.iloc[:, [0, 1, 2, 3, 7, 8, 9, 10, 11]].values
X

array([['Wii', 2006.0, 'Sports', ..., '8', 322.0, 'E'],
       ['Wii', 2008.0, 'Racing', ..., '8.3', 709.0, 'E'],
       ['Wii', 2009.0, 'Sports', ..., '8', 192.0, 'E'],
       ...,
       ['PC', 2014.0, 'Action', ..., '7.6', 412.0, 'M'],
       ['PC', 2011.0, 'Shooter', ..., '5.8', 43.0, 'T'],
       ['PC', 2011.0, 'Strategy', ..., '7.2', 13.0, 'E10+']], dtype=object)

In [16]:
y_na = base.iloc[:, 4].values
y_eu = base.iloc[:, 5].values
y_jp = base.iloc[:, 6].values

In [17]:
y_na

array([4.136e+01, 1.568e+01, 1.561e+01, ..., 0.000e+00, 1.000e-02,
       0.000e+00])

In [18]:
y_eu

array([2.896e+01, 1.276e+01, 1.093e+01, ..., 1.000e-02, 0.000e+00,
       1.000e-02])

In [19]:
y_jp

array([3.77, 3.79, 3.28, ..., 0.  , 0.  , 0.  ])

In [20]:
base['Platform'].value_counts()

Platform
PS2     1140
X360     858
PS3      769
PC       651
XB       565
Wii      479
DS       464
PSP      390
GC       348
PS4      239
GBA      237
XOne     159
3DS      155
PS       150
PSV      118
WiiU      89
DC        14
Name: count, dtype: int64

In [21]:
base.columns

Index(['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Critic_Score', 'Critic_Count', 'User_Score',
       'User_Count', 'Rating'],
      dtype='object')

In [22]:
onehotencoder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [0, 2, 3, 8])], remainder='passthrough')
X = onehotencoder.fit_transform(X).toarray()

In [23]:
X.shape

(6825, 303)

In [24]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.006e+03, 7.600e+01,
       5.100e+01, 8.000e+00, 3.220e+02])

In [25]:
(303 + 3) / 2

153.0

In [26]:
camada_entrada = Input(shape = (303,))
camada_oculta1 = Dense(units = 153, activation='relu')(camada_entrada)
camada_oculta2 = Dense(units = 153, activation='relu')(camada_oculta1)
camada_saida1 = Dense(units = 1, activation='linear')(camada_oculta2)
camada_saida2 = Dense(units = 1, activation='linear')(camada_oculta2)
camada_saida3 = Dense(units = 1, activation='linear')(camada_oculta2)

In [27]:
regressor = Model(inputs = camada_entrada, outputs = [camada_saida1, camada_saida2, camada_saida3])

In [28]:
regressor.compile(optimizer='adam', loss = 'mse')

In [29]:
regressor.fit(X, [y_na, y_eu, y_jp], epochs=500, batch_size=100)

Epoch 1/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - dense_2_loss: 24.2029 - dense_3_loss: 145.2649 - dense_4_loss: 79.0172 - loss: 251.0210
Epoch 2/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 4.7343 - dense_3_loss: 7.5254 - dense_4_loss: 6.8547 - loss: 18.6360
Epoch 3/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 3.2270 - dense_3_loss: 32.5897 - dense_4_loss: 16.5080 - loss: 52.7429
Epoch 4/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 5.6516 - dense_3_loss: 19.3671 - dense_4_loss: 4.4737 - loss: 28.7172
Epoch 5/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 5.3806 - dense_3_loss: 13.9676 - dense_4_loss: 2.9157 - loss: 22.4641
Epoch 6/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 3.2834 - dense_3_loss: 5.8408 - dense_4_loss: 1.3996 - loss: 10.3199
Epoch 7/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 152.0885 - dense_3_loss: 4.8951 - dense_4_loss: 71.3481 - loss: 230.1389
Epoch 8/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 272.3115 - dense_3_loss: 6.8798 - dense_4_loss: 119.6550 - loss: 403.0923
Epoch 9/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.4964 - dense_3_loss: 1.0451 - dense_4_loss: 0.6531 - loss: 3.2230
Epoch 10/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.9034 - dense_3_loss: 0.5615 - dense_4_loss: 0.1913 - loss: 1.6608
Epoch 11/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8445 - dense_3_loss: 0.5092 - dense_4_loss: 0.1715 - loss: 1.5380
Epoch 12/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8392 - dense_3_loss: 0.4857 - dense_4_loss: 0.1452 - loss: 1.4803
Epoch 13/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8536 - dense_3_loss: 0.4704 - dense_4_loss: 0.1866 - loss: 1.5210
Epoch 14/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 0.8327 - dense_3_loss: 0.4760 - dense_4_loss: 0.1784 - loss: 1.4769
Epoch 15/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8070 - dense_3_loss: 0.4470 - dense_4_loss: 0.1550 - loss: 1.4218
Epoch 16/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8917 - dense_3_loss: 0.4338 - dense_4_loss: 0.1895 - loss: 1.5275
Epoch 17/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.8024 - dense_3_loss: 0.4304 - dense_4_loss: 0.1775 - loss: 1.4178
Epoch 18/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8052 - dense_3_loss: 0.4247 - dense_4_loss: 0.1434 - loss: 1.3708
Epoch 19/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7924 - dense_3_loss: 0.4664 - dense_4_loss: 0.2288 - loss: 1.4975
Epoch 20/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8529 - dense_3_loss: 0.4506 - dense_4_loss: 0.1907 - loss: 1.5070
Epoch 21/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8337 - dense_3_loss: 0.4874 - dense_4_loss: 0.2451 - loss: 1.5723
Epoch 22/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9647 - dense_3_loss: 0.4942 - dense_4_loss: 0.2060 - loss: 1.6582
Epoch 23/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 0.9132 - dense_3_loss: 0.4489 - dense_4_loss: 0.2151 - loss: 1.5875
Epoch 24/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8721 - dense_3_loss: 0.4437 - dense_4_loss: 0.1699 - loss: 1.5004
Epoch 25/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8302 - dense_3_loss: 0.4607 - dense_4_loss: 0.1856 - loss: 1.4817
Epoch 26/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8471 - dense_3_loss: 0.4359 - dense_4_loss: 0.2574 - loss: 1.5463
Epoch 27/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8873 - dense_3_loss: 0.5180 - dense_4_loss: 0.3235 - loss: 1.7428
Epoch 28/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8675 - dense_3_loss: 0.5849 - dense_4_loss: 0.7666 - loss: 2.2376
Epoch 29/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0433 - dense_3_loss: 0.5509 - dense_4_loss: 0.4332 - loss: 2.0464
Epoch 30/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9973 - dense_3_loss: 0.8848 - dense_4_loss: 1.0447 - loss: 2.8944
Epoch 31/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9479 - dense_3_loss: 0.7488 - dense_4_loss: 1.0781 - loss: 2.7807
Epoch 32/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0271 - dense_3_loss: 0.9241 - dense_4_loss: 1.6982 - loss: 3.6269
Epoch 33/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1851 - dense_3_loss: 0.5823 - dense_4_loss: 0.4512 - loss: 2.2370
Epoch 34/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1731 - dense_3_loss: 0.5822 - dense_4_loss: 0.5933 - loss: 2.3572
Epoch 35/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9489 - dense_3_loss: 0.6628 - dense_4_loss: 0.9216 - loss: 2.5555
Epoch 36/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 0.8840 - dense_3_loss: 0.6298 - dense_4_loss: 1.0660 - loss: 2.5908
Epoch 37/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.6131 - dense_3_loss: 1.0438 - dense_4_loss: 1.6439 - loss: 4.3316
Epoch 38/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1421 - dense_3_loss: 0.8480 - dense_4_loss: 1.0126 - loss: 3.0164
Epoch 39/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9997 - dense_3_loss: 0.5538 - dense_4_loss: 0.6078 - loss: 2.1733
Epoch 40/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0650 - dense_3_loss: 0.6398 - dense_4_loss: 0.5043 - loss: 2.2247
Epoch 41/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.2606 - dense_3_loss: 1.1682 - dense_4_loss: 1.1121 - loss: 3.5333
Epoch 42/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1339 - dense_3_loss: 1.4436 - dense_4_loss: 1.4315 - loss: 4.0234
Epoch 43/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - dense_2_loss: 1.2535 - dense_3_loss: 3.5203 - dense_4_loss: 1.0081 - loss: 5.6218
Epoch 44/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.3239 - dense_3_loss: 2.5608 - dense_4_loss: 1.8181 - loss: 5.6465
Epoch 45/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.1494 - dense_3_loss: 2.4599 - dense_4_loss: 1.0711 - loss: 4.7003
Epoch 46/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.0790 - dense_3_loss: 1.4534 - dense_4_loss: 0.3154 - loss: 2.8544
Epoch 47/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0051 - dense_3_loss: 0.7695 - dense_4_loss: 0.6927 - loss: 2.4807
Epoch 48/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.9194 - dense_3_loss: 1.1210 - dense_4_loss: 3.4656 - loss: 6.5445
Epoch 49/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.5732 - dense_3_loss: 1.4897 - dense_4_loss: 0.9919 - loss: 4.0712
Epoch 50/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 2.3050 - dense_3_loss: 1.3129 - dense_4_loss: 0.8819 - loss: 4.5090
Epoch 51/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.5503 - dense_3_loss: 1.0795 - dense_4_loss: 0.4400 - loss: 4.0721
Epoch 52/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3713 - dense_3_loss: 1.7374 - dense_4_loss: 0.2683 - loss: 3.3744
Epoch 53/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.5262 - dense_3_loss: 4.7014 - dense_4_loss: 0.8753 - loss: 7.1129
Epoch 54/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.8218 - dense_3_loss: 2.1480 - dense_4_loss: 0.4233 - loss: 4.4304
Epoch 55/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0655 - dense_3_loss: 0.7116 - dense_4_loss: 0.3362 - loss: 2.0520
Epoch 56/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 2.0112 - dense_3_loss: 1.5805 - dense_4_loss: 1.2186 - loss: 4.8422
Epoch 57/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 1.1502 - dense_3_loss: 0.6662 - dense_4_loss: 0.3301 - loss: 2.1497
Epoch 58/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.8803 - dense_3_loss: 0.7859 - dense_4_loss: 0.5739 - loss: 3.2645
Epoch 59/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 1.0210 - dense_3_loss: 0.6307 - dense_4_loss: 0.4612 - loss: 2.1264
Epoch 60/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 1.1261 - dense_3_loss: 0.6155 - dense_4_loss: 0.5742 - loss: 2.3318
Epoch 61/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 2.5930 - dense_3_loss: 1.2660 - dense_4_loss: 0.8470 - loss: 4.6944
Epoch 62/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.8153 - dense_3_loss: 4.4497 - dense_4_loss: 0.8909 - loss: 8.0939
Epoch 63/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 3.2042 - dense_3_loss: 6.1822 - dense_4_loss: 2.0630 - loss: 11.4910
Epoch 64/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.5213 - dense_3_loss: 0.6967 - dense_4_loss: 1.7789 - loss: 3.9955
Epoch 65/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.6594 - dense_3_loss: 0.6355 - dense_4_loss: 1.9326 - loss: 4.2134
Epoch 66/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.9860 - dense_3_loss: 0.7987 - dense_4_loss: 1.5166 - loss: 4.3412
Epoch 67/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0606 - dense_3_loss: 0.5199 - dense_4_loss: 0.2539 - loss: 1.8285
Epoch 68/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3070 - dense_3_loss: 0.7530 - dense_4_loss: 0.2204 - loss: 2.2921
Epoch 69/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 1.2607 - dense_3_loss: 0.9480 - dense_4_loss: 0.2702 - loss: 2.4977
Epoch 70/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3505 - dense_3_loss: 0.5157 - dense_4_loss: 0.2313 - loss: 2.1123
Epoch 71/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.8893 - dense_3_loss: 0.6895 - dense_4_loss: 0.2011 - loss: 2.7050
Epoch 72/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.6186 - dense_3_loss: 0.8287 - dense_4_loss: 0.3775 - loss: 2.8296
Epoch 73/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.5367 - dense_3_loss: 0.5801 - dense_4_loss: 1.0586 - loss: 3.1897
Epoch 74/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.4108 - dense_3_loss: 0.9204 - dense_4_loss: 0.8111 - loss: 3.1560
Epoch 75/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.1795 - dense_3_loss: 0.5903 - dense_4_loss: 1.1815 - loss: 2.9419
Epoch 76/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.4333 - dense_3_loss: 0.9534 - dense_4_loss: 1.3294 - loss: 3.7407
Epoch 77/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - dense_2_loss: 1.0479 - dense_3_loss: 0.7570 - dense_4_loss: 0.6343 - loss: 2.4412
Epoch 78/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - dense_2_loss: 1.8776 - dense_3_loss: 0.6440 - dense_4_loss: 0.2393 - loss: 2.7561
Epoch 79/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.5089 - dense_3_loss: 0.7380 - dense_4_loss: 0.2494 - loss: 2.5103
Epoch 80/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.2062 - dense_3_loss: 0.5328 - dense_4_loss: 0.2856 - loss: 2.0405
Epoch 81/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.9021 - dense_3_loss: 1.2967 - dense_4_loss: 1.2696 - loss: 4.5021
Epoch 82/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 2.0795 - dense_3_loss: 1.5472 - dense_4_loss: 0.8137 - loss: 4.4830
Epoch 83/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 2.1077 - dense_3_loss: 1.1087 - dense_4_loss: 1.1394 - loss: 4.3907
Epoch 84/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 1.5027 - dense_3_loss: 0.7821 - dense_4_loss: 2.2754 - loss: 4.5909
Epoch 85/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.0544 - dense_3_loss: 0.6424 - dense_4_loss: 0.4764 - loss: 2.1818
Epoch 86/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.9933 - dense_3_loss: 0.6304 - dense_4_loss: 0.3723 - loss: 1.9926
Epoch 87/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - dense_2_loss: 1.3334 - dense_3_loss: 0.6919 - dense_4_loss: 0.2220 - loss: 2.2636
Epoch 88/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - dense_2_loss: 1.1323 - dense_3_loss: 0.5723 - dense_4_loss: 0.1421 - loss: 1.8534
Epoch 89/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - dense_2_loss: 1.5341 - dense_3_loss: 1.8388 - dense_4_loss: 0.3557 - loss: 3.4092
Epoch 90/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 2.4013 - dense_3_loss: 7.8807 - dense_4_loss: 1.2861 - loss: 11.6896
Epoch 91/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8259 - dense_3_loss: 0.7372 - dense_4_loss: 0.1749 - loss: 1.7548
Epoch 92/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9138 - dense_3_loss: 0.4935 - dense_4_loss: 0.2169 - loss: 1.6326
Epoch 93/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.0539 - dense_3_loss: 0.4871 - dense_4_loss: 0.1571 - loss: 1.7028
Epoch 94/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - dense_2_loss: 0.9411 - dense_3_loss: 0.4475 - dense_4_loss: 0.2026 - loss: 1.5953
Epoch 95/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9987 - dense_3_loss: 0.6422 - dense_4_loss: 0.7263 - loss: 2.3809
Epoch 96/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8881 - dense_3_loss: 0.5758 - dense_4_loss: 0.4558 - loss: 1.9305
Epoch 97/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.1616 - dense_3_loss: 0.5899 - dense_4_loss: 0.3164 - loss: 2.0801
Epoch 98/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.0363 - dense_3_loss: 0.5414 - dense_4_loss: 0.1488 - loss: 1.7318
Epoch 99/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0695 - dense_3_loss: 0.6496 - dense_4_loss: 0.2421 - loss: 1.9710
Epoch 100/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 1.1418 - dense_3_loss: 0.7028 - dense_4_loss: 0.3426 - loss: 2.2063
Epoch 101/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0593 - dense_3_loss: 0.8163 - dense_4_loss: 0.3967 - loss: 2.2539
Epoch 102/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1258 - dense_3_loss: 0.7266 - dense_4_loss: 0.6840 - loss: 2.5597
Epoch 103/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.9127 - dense_3_loss: 0.5121 - dense_4_loss: 0.2283 - loss: 1.6677
Epoch 104/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9528 - dense_3_loss: 0.5559 - dense_4_loss: 0.4493 - loss: 1.9690
Epoch 105/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - dense_2_loss: 0.9428 - dense_3_loss: 0.5904 - dense_4_loss: 1.4701 - loss: 3.0308
Epoch 106/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - dense_2_loss: 1.1882 - dense_3_loss: 0.6790 - dense_4_loss: 0.2681 - loss: 2.1373
Epoch 107/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - dense_2_loss: 1.0438 - dense_3_loss: 0.5688 - dense_4_loss: 0.1715 - loss: 1.7929
Epoch 108/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - dense_2_loss: 0.9572 - dense_3_loss: 0.4968 - dense_4_loss: 0.1419 - loss: 1.5899
Epoch 109/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - dense_2_loss: 1.0407 - dense_3_loss: 0.6012 - dense_4_loss: 0.4693 - loss: 2.1287
Epoch 110/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - dense_2_loss: 0.9619 - dense_3_loss: 0.5287 - dense_4_loss: 1.0497 - loss: 2.5624
Epoch 111/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.1890 - dense_3_loss: 0.8369 - dense_4_loss: 0.1985 - loss: 2.2122
Epoch 112/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.2104 - dense_3_loss: 1.0341 - dense_4_loss: 1.4074 - loss: 3.6784
Epoch 113/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.9524 - dense_3_loss: 0.6025 - dense_4_loss: 0.2094 - loss: 1.7465
Epoch 114/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9890 - dense_3_loss: 0.5987 - dense_4_loss: 0.1991 - loss: 1.7919
Epoch 115/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 0.9331 - dense_3_loss: 0.5848 - dense_4_loss: 0.2197 - loss: 1.7395
Epoch 116/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.8732 - dense_3_loss: 0.4854 - dense_4_loss: 0.1407 - loss: 1.5077
Epoch 117/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - dense_2_loss: 0.9137 - dense_3_loss: 0.5524 - dense_4_loss: 0.2477 - loss: 1.7103
Epoch 118/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - dense_2_loss: 1.0637 - dense_3_loss: 0.5704 - dense_4_loss: 0.3020 - loss: 1.9356
Epoch 119/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - dense_2_loss: 1.0055 - dense_3_loss: 0.5812 - dense_4_loss: 0.7098 - loss: 2.2987
Epoch 120/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0257 - dense_3_loss: 0.5688 - dense_4_loss: 0.3961 - loss: 2.0045
Epoch 121/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9658 - dense_3_loss: 0.5172 - dense_4_loss: 0.1789 - loss: 1.6619
Epoch 122/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.0147 - dense_3_loss: 0.6080 - dense_4_loss: 0.2445 - loss: 1.8620
Epoch 123/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0005 - dense_3_loss: 0.5551 - dense_4_loss: 0.2660 - loss: 1.8194
Epoch 124/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 1.1394 - dense_3_loss: 0.6766 - dense_4_loss: 0.3934 - loss: 2.2280
Epoch 125/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - dense_2_loss: 1.3471 - dense_3_loss: 0.6910 - dense_4_loss: 0.1643 - loss: 2.1292
Epoch 126/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - dense_2_loss: 1.2926 - dense_3_loss: 0.7147 - dense_4_loss: 0.2050 - loss: 2.1574
Epoch 127/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.2956 - dense_3_loss: 1.6040 - dense_4_loss: 2.5396 - loss: 5.4972
Epoch 128/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8615 - dense_3_loss: 0.5046 - dense_4_loss: 0.1202 - loss: 1.4944
Epoch 129/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8530 - dense_3_loss: 0.4564 - dense_4_loss: 0.1480 - loss: 1.4690
Epoch 130/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.8142 - dense_3_loss: 0.4687 - dense_4_loss: 0.1514 - loss: 1.4331
Epoch 131/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9293 - dense_3_loss: 0.5436 - dense_4_loss: 0.1699 - loss: 1.6470
Epoch 132/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.7982 - dense_3_loss: 0.4974 - dense_4_loss: 0.1840 - loss: 1.4902
Epoch 133/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8341 - dense_3_loss: 0.4821 - dense_4_loss: 0.1404 - loss: 1.4648
Epoch 134/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - dense_2_loss: 0.9186 - dense_3_loss: 0.5943 - dense_4_loss: 0.1379 - loss: 1.6597
Epoch 135/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - dense_2_loss: 1.1418 - dense_3_loss: 0.7472 - dense_4_loss: 0.2689 - loss: 2.1737
Epoch 136/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - dense_2_loss: 0.9046 - dense_3_loss: 0.5772 - dense_4_loss: 0.2522 - loss: 1.7417
Epoch 137/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.7853 - dense_3_loss: 0.4762 - dense_4_loss: 0.2056 - loss: 1.4805
Epoch 138/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8696 - dense_3_loss: 0.5050 - dense_4_loss: 0.1232 - loss: 1.5050
Epoch 139/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.9449 - dense_3_loss: 0.6284 - dense_4_loss: 0.1890 - loss: 1.7194
Epoch 140/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.9867 - dense_3_loss: 0.7036 - dense_4_loss: 0.4297 - loss: 2.1358
Epoch 141/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0200 - dense_3_loss: 0.6130 - dense_4_loss: 0.2159 - loss: 1.8593
Epoch 142/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.9207 - dense_3_loss: 0.5786 - dense_4_loss: 0.2038 - loss: 1.7042
Epoch 143/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 1.1277 - dense_3_loss: 0.8560 - dense_4_loss: 0.2563 - loss: 2.2205
Epoch 144/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.8361 - dense_3_loss: 0.8518 - dense_4_loss: 0.7928 - loss: 2.4796
Epoch 145/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.8235 - dense_3_loss: 0.4706 - dense_4_loss: 0.1091 - loss: 1.4141
Epoch 146/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.8361 - dense_3_loss: 0.4884 - dense_4_loss: 0.1035 - loss: 1.4307
Epoch 147/500

In [30]:
previsao_na, previsao_eu, previsao_jp = regressor.predict(X) # Testando o modelo com os próprios dados de treinamento

214/214 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [31]:
previsao_na, previsao_na.mean()

(array([[15.68995   ],
        [12.828206  ],
        [16.748383  ],
        ...,
        [ 0.27130085],
        [ 0.27373138],
        [ 0.22394893]], dtype=float32),
 np.float32(0.49679095))

In [32]:
y_na, y_na.mean()

(array([4.136e+01, 1.568e+01, 1.561e+01, ..., 0.000e+00, 1.000e-02,
        0.000e+00]),
 np.float64(0.3944835164835165))

In [33]:
from sklearn.metrics import mean_absolute_error

In [34]:
mean_absolute_error(y_na, previsao_na)

0.34626159069284845

In [35]:
previsao_eu, previsao_eu.mean()

(array([[11.068988  ],
        [ 9.052471  ],
        [11.774262  ],
        ...,
        [ 0.19282827],
        [ 0.14144272],
        [ 0.10891548]], dtype=float32),
 np.float32(0.2955004))

In [36]:
y_eu, y_eu.mean()

(array([2.896e+01, 1.276e+01, 1.093e+01, ..., 1.000e-02, 0.000e+00,
        1.000e-02]),
 np.float64(0.23608937728937732))

In [37]:
mean_absolute_error(y_eu, previsao_eu)

0.23042358326134663

In [38]:
previsao_jp, previsao_jp.mean()

(array([[ 3.4923449 ],
        [ 3.2920475 ],
        [ 3.4498754 ],
        ...,
        [ 0.02761116],
        [-0.02190124],
        [-0.04034866]], dtype=float32),
 np.float32(0.051064234))

In [39]:
y_jp, y_jp.mean()

(array([3.77, 3.79, 3.28, ..., 0.  , 0.  , 0.  ]),
 np.float64(0.06415824175824175))

In [40]:
mean_absolute_error(y_jp, previsao_jp)

0.08030507266855502